<?xml version="1.0" encoding="utf-8"?><Database Name="Sanitation.BPM" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=Sanitation.BPM;User ID=sa;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="SanitationServer2.Properties.Settings" SettingsPropertyName="Sanitation_BPMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sanitation_Dispatch" Member="Sanitation_Dispatch">
    <Type Name="Sanitation_Dispatch">
      <Column Name="KeyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DriverId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrunkId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Kind" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Potency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Volumn" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="Destination" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Region" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Signed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Working" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Memo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Sanitation_Driver" Member="Sanitation_Driver">
    <Type Name="Sanitation_Driver">
      <Column Name="KeyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telphone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memo" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Sanitation_Trunk" Member="Sanitation_Trunk">
    <Type Name="Sanitation_Trunk">
      <Column Name="KeyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Plate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Volumn" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" CanBeNull="false" />
      <Column Name="Memo" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Gps" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IpAddress" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="LastTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>