<?xml version="1.0" encoding="utf-8"?><Database Name="WasherBusiness" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=WasherBusiness;Integrated Security=True" SettingsObjectName="WasherBusiness.Properties.Settings" SettingsPropertyName="WasherBusinessConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BoardCommand" Member="BoardCommand">
    <Type Name="BoardCommand">
      <Column Name="KeyId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Board" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Command" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Direction" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>